container:
  image: golang:latest

task:
  matrix:
     - name: linux
       fmt_script: diff -au <(gofmt -d .) <(printf "")
  
  - osx_instance:
      image: mojave-base
    matrix:
      - name: macOS
        fmt_script: diff -au <(gofmt -d .) <(printf "")     
   
  modules_cache:
     fingerprint_script: cat go.sum
     folder: $GOPATH/pkg/mod
  get_script: go get ./...
  vet_script: diff -au <(go vet .) <(printf "")
  build_script: go build ./...
  test_script: go test ./...
