task:
   matrix:
      - name: linux
        container:
           image: golang:latest
      
      - name: macOS
        osx_instance:
           image: mojave-base
        env:
           VERSION: 1.12.7
           PATH: /usr/local/go/bin:${PATH}
        install_script:
           - rm -rfv /usr/local/go
           - curl https://dl.google.com/go/go${VERSION}.darwin-amd64.tar.gz | tar -xz -C /usr/local

  
   modules_cache:
       fingerprint_script: cat go.sum
       folder: $GOPATH/pkg/mod
   check_script: 
       - diff -au <(gofmt -d .) <(printf "")
       - diff -au <(go vet .) <(printf "")
   get_script:
      - go get ./...
      - go build ./...
   test_script: go test ./...
     
